<a href="https://colab.research.google.com/github/vimalkumarasamy/computer_vision/blob/master/CV_homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
arr=np.array([[2,1,2,1,1,2,1,2,1,1],[1,2,1,1,2,1,1,1,1,2],[2,2,1,2,1,2,2,1,2,1],[2,1,1,1,2,1,2,1,2,1],[1,2,2,1,1,1,1,2,1,2],[2,2,1,1,2,2,1,1,2,1],[1,1,1,2,1,1,2,2,2,1],[2,1,2,1,1,2,1,2,1,1],[1,3,1,1,2,1,1,1,1,1],[2,2,1,2,1,2,2,1,2,2]])
arr=arr-1

In [45]:
ones=0
zeros=0
matches=np.zeros(arr.shape)
for i in range(1,arr.shape[0]-1):
  for j in range(1,arr.shape[1]-1):
    if arr[i,j-1]==0 and arr[i-1,j-1]==1 and arr[i-1,j]==0 and arr[i-1,j+1]==1 and arr[i,j+1]==0 and arr[i+1,j-1]==1 and arr[i+1,j]==1 and arr[i+1,j+1]==0:
      
      if arr[i,j]==1 :
        ones=ones+1
        matches[i,j]=100
      if arr[i,j]==0 :
        zeros=zeros+1
        matches[i,j]=50
      # pass
print("light shades are :", ones, "\ndark shades are :", zeros, "\nprob of dark shade :",zeros/(zeros+ones)*100,"%")
print(matches)

light shades are : 2 
dark shades are : 4 
prob of dark shade : 66.66666666666666 %
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 100.   0.   0.   0.   0.  50.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  50.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  50.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 100.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  50.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


In [46]:
ones=0
zeros=0
matches=np.zeros(arr.shape)
for i in range(1,arr.shape[0]-1):
  for j in range(1,arr.shape[1]-1):
    if arr[i,j-1]==0 and arr[i-1,j]==0 and arr[i,j+1]==0 and arr[i+1,j]==1:
      
      if arr[i,j]==1 :
        ones=ones+1
        matches[i,j]=100
      if arr[i,j]==0 :
        zeros=zeros+1
        matches[i,j]=50
      # pass
print("light shades are :", ones, "\ndark shades are :", zeros, "\nprob of dark shade :",zeros/(zeros+ones)*100,"%")
print(matches)

light shades are : 3 
dark shades are : 5 
prob of dark shade : 62.5 %
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 100.   0.   0.   0.   0.  50.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 100.   0.]
 [  0.   0.  50.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  50.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0. 100.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.  50.   0.  50.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
