<a href="https://colab.research.google.com/github/vimalkumarasamy/computer_vision/blob/master/Filter_and_rotation_matrix_design.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Design a 5x5 flter which can shift image down by 2 pixels and to the left 1 pixel.

In [0]:
def padding(mat,value):
  a,b=mat.shape
  out_mat=np.zeros((a+(2*value), b+(2*value)))
  for i in range(a):
    for j in range(b):
      out_mat[i+value][j+value]=mat[i][j]
  return(out_mat)

In [0]:
import numpy as np 
import random
N=3
arr=np.array([[random.random()]*N for x in range(N)])

F1 = np.array([[0, 0, 1, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

def apply_filter(input_array,filter):
  arr=input_array.copy()
  F1=filter.copy()
  a,b=arr.shape
  arr_pad=padding(arr,2)
  out_mat=np.zeros((a, b))
  for i in range(a):
    for j in range(b):
      out_mat[i][j]=(np.multiply(arr_pad[i:i+5,j:j+5],F1)).sum()
  return(out_mat)



In [140]:
F1 = np.array([[0, 0, 1, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

F2 = np.array([[0, 0, 0, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

F3=np.matmul(F1,F2)
print(arr)
# apply_filter(arr,F2)

[[0.85163601 0.85163601 0.85163601 0.85163601 0.85163601 0.85163601]
 [0.96191285 0.96191285 0.96191285 0.96191285 0.96191285 0.96191285]
 [0.41745829 0.41745829 0.41745829 0.41745829 0.41745829 0.41745829]
 [0.45806308 0.45806308 0.45806308 0.45806308 0.45806308 0.45806308]
 [0.72386475 0.72386475 0.72386475 0.72386475 0.72386475 0.72386475]
 [0.37386656 0.37386656 0.37386656 0.37386656 0.37386656 0.37386656]]


In [141]:
arr

array([[0.85163601, 0.85163601, 0.85163601, 0.85163601, 0.85163601,
        0.85163601],
       [0.96191285, 0.96191285, 0.96191285, 0.96191285, 0.96191285,
        0.96191285],
       [0.41745829, 0.41745829, 0.41745829, 0.41745829, 0.41745829,
        0.41745829],
       [0.45806308, 0.45806308, 0.45806308, 0.45806308, 0.45806308,
        0.45806308],
       [0.72386475, 0.72386475, 0.72386475, 0.72386475, 0.72386475,
        0.72386475],
       [0.37386656, 0.37386656, 0.37386656, 0.37386656, 0.37386656,
        0.37386656]])

In [142]:
apply_filter(arr,F1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.85163601, 0.85163601, 0.85163601, 0.85163601, 0.85163601,
        0.85163601],
       [0.96191285, 0.96191285, 0.96191285, 0.96191285, 0.96191285,
        0.96191285],
       [0.41745829, 0.41745829, 0.41745829, 0.41745829, 0.41745829,
        0.41745829],
       [0.45806308, 0.45806308, 0.45806308, 0.45806308, 0.45806308,
        0.45806308]])

In [143]:
apply_filter(arr,F2)

array([[0.85163601, 0.85163601, 0.85163601, 0.85163601, 0.85163601,
        0.        ],
       [0.96191285, 0.96191285, 0.96191285, 0.96191285, 0.96191285,
        0.        ],
       [0.41745829, 0.41745829, 0.41745829, 0.41745829, 0.41745829,
        0.        ],
       [0.45806308, 0.45806308, 0.45806308, 0.45806308, 0.45806308,
        0.        ],
       [0.72386475, 0.72386475, 0.72386475, 0.72386475, 0.72386475,
        0.        ],
       [0.37386656, 0.37386656, 0.37386656, 0.37386656, 0.37386656,
        0.        ]])

In [147]:
apply_filter(arr,F3)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.83747199, 0.83747199, 0.        ]])

In [148]:
arr

array([[0.83747199, 0.83747199, 0.83747199],
       [0.19669369, 0.19669369, 0.19669369],
       [0.86966281, 0.86966281, 0.86966281]])

In [149]:
F3

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [150]:
F1

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [151]:
F2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [0]:
# Rotation across XY plane in 2 dimension

In [0]:
import math
import numpy as np
theta=math.pi/2
d_2 = np.array([[math.cos(theta), -math.sin(theta)], 
                [math.sin(theta), math.cos(theta)]])

co_ord = np.array([[1],[1]])

In [16]:
np.matmul(d_2,co_ord)

array([[-1.],
       [ 1.]])

In [17]:
co_ord

array([[1],
       [1]])