<a href="https://colab.research.google.com/github/vimalkumarasamy/computer_vision/blob/master/Filter_Design_and_rotation_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# 1. Rotating an image across different axes
import math
# dimensional rotations
theta=math.pi/2
Rx=np.array([[1,0,0],  
             [0,math.cos(theta), -math.sin(theta)],
             [0, math.sin(theta),math.cos(theta)]])

Ry=np.array([[math.cos(theta),0,math.sin(theta)],  
             [0,1, 0],
             [-math.sin(theta),0,math.cos(theta)]])

Rz=np.array([[math.cos(theta),-math.sin(theta),0],  
             [math.sin(theta),math.cos(theta), 0],
             [0, 0,1]])
A = np.array([[10],[0],[20]])
Rzy=np.matmul(Ry,Rz)
print(np.matmul(Rzy,A))
# [20,10,0]
print(Rzy)
# [ 0, 0, 1]
# [ 1, 0, 0]
# [ 0, 1, 0]

[[2.000000e+01]
 [1.000000e+01]
 [6.123234e-16]]
[[ 3.74939946e-33 -6.12323400e-17  1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00]
 [-6.12323400e-17  1.00000000e+00  6.12323400e-17]]


In [0]:
# 2. Scene coordinates to image coordinates translation 
# Suppose we have the following intrinsic parameters of camera: focal length is 2, the coordinate of
# image center is [10; 10] . There is unit aspect ratio and no skew of the pixels.
# If the coordinate of a point is [0; 2; 1] in the camera coordinate, calculate its coordinate on the image
# plane.
# Determine the intrinsic matrix.
# Give the coordinate on the image plane

# Scene to image translation 
k=np.array([[2,0,10],
            [0,2,10],
            [0,0,1]])

R_t=np.array([[1,0,0,0],
              [0,1,0,0],
              [0,0,1,0]])

A=np.array([[0],[2],[1],[1]])

np.matmul(np.matmul(k,R_t),A)

array([[10],
       [14],
       [ 1]])

In [0]:
# 3. Design a 5x5 flter which can shift image down by 2 pixels and to the left 1 pixel.
# Utility function to introduce padding
def padding(mat,value):
  a,b=mat.shape
  out_mat=np.zeros((a+(2*value), b+(2*value)))
  for i in range(a):
    for j in range(b):
      out_mat[i+value][j+value]=mat[i][j]
  return(out_mat)

# Utility function that applies a filter
def apply_filter(input_array,filter):
  arr=input_array.copy()
  F1=filter.copy()
  a,b=arr.shape
  arr_pad=padding(arr,2)
  out_mat=np.zeros((a, b))
  for i in range(a):
    for j in range(b):
      out_mat[i][j]=(np.multiply(arr_pad[i:i+5,j:j+5],F1)).sum()
  return(out_mat)

import numpy as np 

# sample input matrix
arr= np.array([[ 1,  2,  3,  4,  5], 
               [ 6,  7,  8,  9, 10],
               [11, 12, 13, 14, 15],
               [16, 17, 18, 19, 20],
               [21, 22, 23, 24, 25]])

# Filter that shifts the pixels down by 2 units
F1 = np.array([[0, 0, 1, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

# Filter that shifts the pixels left by 1 units
F2 = np.array([[0, 0, 0, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

# Combining the filters
F3=np.matmul(F1,F2)

print(arr)
print(apply_filter(arr,F3))
print(F3)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 2.  3.  4.  5.  0.]
 [ 7.  8.  9. 10.  0.]
 [12. 13. 14. 15.  0.]]
[[0 0 0 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [0]:
theta=math.pi/2
Rx=np.array([[1,0,0],  
             [0,math.cos(theta), -math.sin(theta)],
             [0, math.sin(theta),math.cos(theta)]])

Ry=np.array([[math.cos(theta),0,math.sin(theta)],  
             [0,1, 0],
             [-math.sin(theta),0,math.cos(theta)]])

Rz=np.array([[math.cos(theta),-math.sin(theta),0],  
             [math.sin(theta),math.cos(theta), 0],
             [0, 0,1]])
A = np.array([[1],[1],[1]])
B = np.matmul(Rz,A)
print(B)

[[-1.]
 [ 1.]
 [ 1.]]


In [0]:
import numpy as np


In [0]:
a=np.array([[1,2,1]])
b=np.array([[1],[2],[1]])

In [22]:
(np.multiply(a,b)).tolist()

[[1, 2, 1], [2, 4, 2], [1, 2, 1]]

In [0]:
a=np.array([[1,2,3],[1,2,4],[2,3,4]])

In [0]:
G1=np.array([[1,2,1]])

In [0]:
G2=np.transpose(G1)

In [26]:
np.multiply(G2,np.multiply(G1,a))

array([[1, 4, 3],
       [2, 8, 8],
       [2, 6, 4]])

In [27]:
G=np.multiply(G2,G1)
np.multiply(G,a)

array([[1, 4, 3],
       [2, 8, 8],
       [2, 6, 4]])

In [28]:
a

array([[1, 2, 3],
       [1, 2, 4],
       [2, 3, 4]])

In [29]:
G

array([[1, 2, 1],
       [2, 4, 2],
       [1, 2, 1]])

In [30]:
np.multiply(G1,a)

array([[1, 4, 3],
       [1, 4, 4],
       [2, 6, 4]])

In [31]:
G


array([[1, 2, 1],
       [2, 4, 2],
       [1, 2, 1]])

In [32]:
G1

array([[1, 2, 1]])

In [33]:
G2

array([[1],
       [2],
       [1]])