<a href="https://colab.research.google.com/github/vimalkumarasamy/computer_vision/blob/master/Filter_Design_and_rotation_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Design a 5x5 flter which can shift image down by 2 pixels and to the left 1 pixel.

In [0]:
def padding(mat,value):
  a,b=mat.shape
  out_mat=np.zeros((a+(2*value), b+(2*value)))
  for i in range(a):
    for j in range(b):
      out_mat[i+value][j+value]=mat[i][j]
  return(out_mat)

In [0]:
import numpy as np 
import random
N=3
arr=np.array([[random.random()]*N for x in range(N)])

F1 = np.array([[0, 0, 1, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

def apply_filter(input_array,filter):
  arr=input_array.copy()
  F1=filter.copy()
  a,b=arr.shape
  arr_pad=padding(arr,2)
  out_mat=np.zeros((a, b))
  for i in range(a):
    for j in range(b):
      out_mat[i][j]=(np.multiply(arr_pad[i:i+5,j:j+5],F1)).sum()
  return(out_mat)



In [4]:
F1 = np.array([[0, 0, 1, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

F2 = np.array([[0, 0, 0, 0, 0], 
               [0, 0, 0, 0, 0],
               [0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0]])

F3=np.matmul(F1,F2)
print(arr)
# apply_filter(arr,F2)

[[0.04193627 0.04193627 0.04193627]
 [0.16832363 0.16832363 0.16832363]
 [0.65135636 0.65135636 0.65135636]]


In [5]:
arr

array([[0.04193627, 0.04193627, 0.04193627],
       [0.16832363, 0.16832363, 0.16832363],
       [0.65135636, 0.65135636, 0.65135636]])

In [6]:
apply_filter(arr,F1)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.04193627, 0.04193627, 0.04193627]])

In [7]:
apply_filter(arr,F2)

array([[0.04193627, 0.04193627, 0.        ],
       [0.16832363, 0.16832363, 0.        ],
       [0.65135636, 0.65135636, 0.        ]])

In [8]:
apply_filter(arr,F3)

array([[0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.04193627, 0.04193627, 0.        ]])

In [9]:
arr

array([[0.04193627, 0.04193627, 0.04193627],
       [0.16832363, 0.16832363, 0.16832363],
       [0.65135636, 0.65135636, 0.65135636]])

In [10]:
F3

array([[0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
F1

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
F2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [0]:
# Rotation across XY plane in 2 dimension

In [0]:
import math
import numpy as np
theta=math.pi/2
d_2 = np.array([[math.cos(theta), -math.sin(theta)], 
                [math.sin(theta), math.cos(theta)]])

co_ord = np.array([[1],[1]])

In [15]:
np.matmul(d_2,co_ord)

array([[-1.],
       [ 1.]])

In [16]:
co_ord

array([[1],
       [1]])

In [0]:
# dimensional rotations

Rx=np.array([[1,0,0],  
             [0,math.cos(theta), -math.sin(theta)],
             [0, math.sin(theta),math.cos(theta)]])

Ry=np.array([[math.cos(theta),0,math.sin(theta)],  
             [0,1, 0],
             [-math.sin(theta),0,math.cos(theta)]])

Rz=np.array([[math.cos(theta),-math.sin(theta),0],  
             [math.sin(theta),math.cos(theta), 0],
             [0, 0,1]])




In [31]:
theta=math.pi/2
A = np.array([[10],[0],[20]])
Rzy=np.matmul(Ry,Rz)
np.matmul(Rzy,A)
# [20,10,0]

array([[2.000000e+01],
       [1.000000e+01],
       [6.123234e-16]])

In [33]:
print(Rzy)
# [ 0, 0, 1]
# [ 1, 0, 0]
# [ 0, 1, 0]



[[ 3.74939946e-33 -6.12323400e-17  1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  0.00000000e+00]
 [-6.12323400e-17  1.00000000e+00  6.12323400e-17]]
